### ISSUE TITLE
Missing how can I install the App to production store

### ISSUE THREAD

**Issue by lezan** [edlaver/cloudflare-worker-partytown-shopify-app-proxy#1]
Hello there,
I am trying to use your repo to run Partytown on Shopify but I am getting some issues mainly because it is my first time with Shopify and App.
I am missing how can I install the custom App in my main store. Can you give a direction?

Thanks in advance!

**Comment by edlaver** [comment]
Hi @lezan, thanks for reaching out.

Do you have a Shopify Partners account?

If so, you could either choose to distribute your app via a "custom install" link and add it to your store, or choose Public Distribution and leave it as an unlisted app.

See: https://shopify.dev/docs/apps/distribution/select-distribution-method

Feel free to reach out on Discord, my username there is: `edlaver`

**Comment by lezan** [comment]
Hello @edlaver, thanks for a so quickly reply! Much appreciated.

> Do you have a Shopify Partners account?

 Yes, I have.

> If so, you could either choose to distribute your app via a "custom install" link and add it to your store, or choose Public Distribution and leave it as an unlisted app.

Custom install is what I did but I thought I was missing something in the App hosted on Cloudflare (or in the App configuration in Shopify) because I always got the "nothing". I thought I was missing autenthification process in the App located in Cloudflare and also URLs section in the Shopify App, so I did some research and find [that](https://shopify.dev/docs/apps/auth/get-access-tokens/authorization-code-grant/getting-started). I followed it I got "Unauthorized Access:". I tried with incognito mod and I got "The installation link for this app is invalid". Attached two screenshot (sorry for the second one, it is not english, but the message is "The installation link for this app is invalid").

So if I can ask:
- Is the authentification required? Because it is not implemented in your workers and it is not reported in your step by step repo.
- I also configure the URLs section in Shopify App with two endpoint for the authentification process. That's correct?

Sorry for all my questions!

![incognito](https://github.com/edlaver/cloudflare-worker-partytown-shopify-app-proxy/assets/1663016/fb5df7b5-542c-4cb8-acb9-ed96bfc32e6e)
![no-incognito](https://github.com/edlaver/cloudflare-worker-partytown-shopify-app-proxy/assets/1663016/540e4d64-357a-473b-ace4-4fe0ce45ef0f)

**Comment by edlaver** [comment]
Hi @lezan, the Shopify app isn't related to the Cloudflare Worker really.

You only need an app in order to set the `App proxy`, to create a tunnel from your storefront through to Cloudflare Worker.

That's the only place that should point to the Cloudflare Worker, you should **not** point at that endpoint in the app setup (other than the App Proxy section).

And you'll only need the app to point to somewhere when you first install it.  In order for it to be installed it needs to go through an auth process.

This could be a default app which you create with the Shopify CLI: https://shopify.dev/docs/apps/tools/cli

I haven't used it in a while, but I think from memory when you run it, it creates a tunnel that gives you an HTTPS endpoint that can be used for app installation (e.g. it creates a URL in the App > Configuration > URLs section)

![image](https://github.com/edlaver/cloudflare-worker-partytown-shopify-app-proxy/assets/56447343/d14f8358-5565-4f58-bc0f-6d17f86d7037)

Another option could be to use [Gadget.dev ](https://gadget.dev/).  That's probably the simplest way to create an app and get an endpoint you can add to that config section.

See: https://docs.gadget.dev/guides/getting-started/shopify-quickstart

**Comment by lezan** [comment]
Hello @edlaver, thank you so much for point out!

For some reason I thought I need authorization in the same place of the App proxy, so I was trying to make the Oauth 2.0 process from the itty-router app hosted in Cloudflare Workers. Instead it was so simple:
- create a skeleton app from the Shopify CLI.
- Install on Development store.
- Create the App in dev store. The URLs section is auto configured by the CLI.
- Change according to your step by step guide the App proxy.
- Create custom distribution from the Dev account.
- Install the App with the Install link in the main shop.

So easy.

Again, thank you so much the the quickly answers and
